import { createBadgeIcon } from './icon-base';
export { CurrencyDemoIcon, CurrencyUsdIcon } from '@deriv/quill-icons/Currencies';

const currencyIcon = (label: string, accent?: string, background?: string) =>
    createBadgeIcon({ label, accent, background });

export const CurrencyAudIcon = currencyIcon('AUD', '#0f766e', '#ecfeff');
export const CurrencyBchIcon = currencyIcon('BCH', '#92400e', '#fff7ed');
export const CurrencyBtcIcon = currencyIcon('BTC', '#b45309', '#fffbeb');
export const CurrencyBusdIcon = currencyIcon('BUSD', '#166534', '#ecfdf5');
export const CurrencyDaiIcon = currencyIcon('DAI', '#854d0e', '#fefce8');
export const CurrencyEthIcon = currencyIcon('ETH', '#4338ca', '#eef2ff');
export const CurrencyEurIcon = currencyIcon('EUR', '#1d4ed8', '#eff6ff');
export const CurrencyEursIcon = currencyIcon('EURS', '#1e40af', '#eff6ff');
export const CurrencyGbpIcon = currencyIcon('GBP', '#7c3aed', '#f5f3ff');
export const CurrencyIdkIcon = currencyIcon('IDK', '#0f766e', '#f0fdfa');
export const CurrencyLtcIcon = currencyIcon('LTC', '#475569', '#f8fafc');
export const CurrencyPaxIcon = currencyIcon('PAX', '#065f46', '#ecfdf5');
export const CurrencyTusdIcon = currencyIcon('TUSD', '#0f766e', '#f0fdfa');
export const CurrencyUsdtIcon = currencyIcon('USDT', '#166534', '#ecfdf5');
export const CurrencyUsdcIcon = currencyIcon('USDC', '#1d4ed8', '#eff6ff');
export const CurrencyUsdkIcon = currencyIcon('USDK', '#1d4ed8', '#eff6ff');
export const CurrencyXrpIcon = currencyIcon('XRP', '#374151', '#f9fafb');
export const CurrencyAlgoIcon = currencyIcon('ALGO', '#111827', '#f3f4f6');
export const CurrencyAvaxIcon = currencyIcon('AVAX', '#b91c1c', '#fef2f2');
export const CurrencyBatIcon = currencyIcon('BAT', '#b45309', '#fff7ed');
export const CurrencyBnbIcon = currencyIcon('BNB', '#ca8a04', '#fefce8');
export const CurrencyDashIcon = currencyIcon('DASH', '#1d4ed8', '#eff6ff');
export const CurrencyDogeIcon = currencyIcon('DOGE', '#ca8a04', '#fefce8');
export const CurrencyDotIcon = currencyIcon('DOT', '#be185d', '#fdf2f8');
export const CurrencyEosIcon = currencyIcon('EOS', '#111827', '#f9fafb');
export const CurrencyEtcIcon = currencyIcon('ETC', '#166534', '#ecfdf5');
export const CurrencyFilIcon = currencyIcon('FIL', '#0f766e', '#f0fdfa');
export const CurrencyIotaIcon = currencyIcon('IOTA', '#111827', '#f3f4f6');
export const CurrencyLinkIcon = currencyIcon('LINK', '#1d4ed8', '#eff6ff');
export const CurrencyMaticIcon = currencyIcon('MATIC', '#6d28d9', '#f5f3ff');
export const CurrencyMkrIcon = currencyIcon('MKR', '#0f766e', '#f0fdfa');
export const CurrencyMultiCollateralDaiIcon = currencyIcon('MCD', '#854d0e', '#fefce8');
export const CurrencyNeoIcon = currencyIcon('NEO', '#166534', '#ecfdf5');
export const CurrencyNoneIcon = currencyIcon('--', '#64748b', '#f8fafc');
export const CurrencyOmgIcon = currencyIcon('OMG', '#2563eb', '#eff6ff');
export const CurrencyP2PIcon = currencyIcon('P2P', '#0f766e', '#f0fdfa');
export const CurrencySingleCollateralDaiIcon = currencyIcon('SCD', '#854d0e', '#fefce8');
export const CurrencySolIcon = currencyIcon('SOL', '#7c3aed', '#f5f3ff');
export const CurrencyTerraIcon = currencyIcon('LUNA', '#1d4ed8', '#eff6ff');
export const CurrencyTrxIcon = currencyIcon('TRX', '#b91c1c', '#fef2f2');
export const CurrencyUniIcon = currencyIcon('UNI', '#db2777', '#fdf2f8');
export const CurrencyXlmIcon = currencyIcon('XLM', '#0f172a', '#f8fafc');
export const CurrencyXmrIcon = currencyIcon('XMR', '#c2410c', '#fff7ed');
export const CurrencyXtzIcon = currencyIcon('XTZ', '#2563eb', '#eff6ff');
export const CurrencyZecIcon = currencyIcon('ZEC', '#a16207', '#fefce8');
export const CurrencyPlaceholderIcon = currencyIcon('???', '#64748b', '#f8fafc');
